#!/bin/bash
#
CST_NAME="cstpkg"
CST_CONFIGDIR="/etc/${CST_NAME}.d"
CST_LOCALCONFIGDIR="${HOME}/.${CST_NAME}"
CST_LIBDIR="/usr/lib/cstpkg"
#CST_LIBDIR="/home/marko/Documents/projects/bash/cstpkg/lib"

hooksfile="PKGBUILD.func" # consist of only functions (build,prepare,check,package)
tmpfile="PKGBUILD.tmp" 
backupfile="PKGBUILD.original"

# Load core functions
source "${CST_LIBDIR}/core.bash" || exit 255

# Load necessary functions for the main script
include colours

# use colordiff if it's available
[[ $(type -p colordiff) ]] && DIFFCMD="colordiff -ub" || DIFFCMD="diff -ub"

do_patch(){
	local scriptfile=${1} diff=${2}
	
	info -m "Patching ${scriptfile} with ${diff}"	
		patch --quiet "${scriptfile}" < ${diff} || \
			(info -e "Something wen't wrong while patching ${scriptfile}" && return 127)
	
	return 0 # E_SUCCESS
}

do_clean(){
	local destroy="${hooksfile} ${tmpfile} ${tmpfile}.orig hooks_* \
		*.cstpkg update-vars* PKGBUILD.upstream PKGBUILD.${package}"
	
	info -m "Removing work files bellow:"
	for i in ${destroy[@]}; do 
		[[ -f $i ]] && info -a "$i" && rm $i
	done
}

modify_file(){
	local configfile=$1 originalscriptfile=$2 scriptfile=$3

	# NOTE: DO I NEED THIS, WILL I ALLOW THIS KIND OF METHOD?
	# if the customize file is executable, run it, then we're done.
	if [ -x "${configfile}" ]; then
		info -m "${configfile} is executable, so treating it as a script instead of config"
		"${configfile}" "${originalscriptfile}" "${scriptfile}" && return 0 || exit 1
	fi

	grep "^%" ${configfile} |
	while read -r action context pattern; do
		case ${action} in
			%config )
					include savedconfig
					restore_config "${context}" || return #E_CODE=125
				;;
			%update-vars )
					include child_parrent
					[[ $(is_parent_or_child) == 'child' ]] && parrent=$(is_child_of) && \
						info -m "Don't need to update, child process of ${Y}${parrent}${N}" && return 0

					include downloader
					local git=0 fallback=0
					
					# git or bzr or svn ...
					[[ ${package} =~ \-git ]] && git=1
					
					info -m "updating PKGBUILD vars from usptream"
					
					# PKGBUILD must exist in $CONFIGDIR/$package. If not it will fallback to upstream ver
					# and with him we can update var with new one from upstream servers
					validate_and_copy_file "PKGBUILD.${package}"  || fallback=1
					
					# fetch PKGBUILD 
					getpkgbuild "${context}" "./PKGBUILD.upstream"
					# create diff between ./PKGBUILD and PKGBUILD upstream
					diff -ub <(sed -n "1,/^[a-z].*()/p" ./PKGBUILD | head -n -1 ) \
					<(sed -n "1,/^[a-z].*()/p" ./PKGBUILD.upstream | head -n -1) \
					> ./update-vars.diff
					
					# finaly patch PKGBUILD
					do_patch "${scriptfile}" "./update-vars.diff" || return
					
					# if PKGBUILD.${package} doesn't exist ignore all this bellow: otherwise 
					# remove all function from PKGBUILD.tmp as we will replace them
					# with our function from /etc PKGBUILD.audit
					# also add removed function from PKGBUILD.${package}
					if ! (( $fallback )); then 
						sed -i "/^[a-zA-Z].*() {/,/^}\n/d" "${scriptfile}"
						sed -n "/^[a-zA-Z].*() {/,/^}\n/p" "./PKGBUILD.${package}" >> ${scriptfile}
					fi
				;;
			# TODO: add strict nonstrict 	
			* )
				info -e "There is no such action: ${action}" 1>&2
				exit 255
				;;
		esac
	done

	# immediately exit from program if error occour
	E_CODE=$(error_handling)
	[[ $E_CODE != 0 ]] && return $E_CODE

	grep --invert-match "\(^#\|^$\|^%\)" ${configfile} |
	while IFS='#' read -r action context pattern value ovalue; do
		case ${action} in
			replace)
					#value="${value//\'}"
					case ${context} in
						global ) 
							info -m "replaces '${pattern}' with '${value}' in ${context}"
							case ${pattern} in
								makedepends|optdepends|depends)
									pattern="${pattern}[<>=]*\(: \|\)[a-z0-9.{$}\-]*"
									sed -i "/^${context}=/,/)$/ s|${pattern}|${value}|g" "${scriptfile}" ;;
								* )
									sed -i "s|${pattern}|${value}|g" "${scriptfile}" ;;
							esac ;;
						function ) 
							#	example: replace#function#build()
							info -m "diff hook '${pattern}' from ${hooksfile}"
							
							validate_and_copy_file "${hooksfile}" || return

							#<(sed -n "/${value}/,/^}/p" "./PKGBUILD.hooks" ) \
							diff -ub <(sed -n "/${pattern}/,/^}/p" ${scriptfile}) \
							<(sed -n "/${pattern}/,/^}/p" "./${hooksfile}" ) \
							> ./hooks_${pattern}.diff
							 
							info -m "Patching ${scriptfile} with ./hook_${pattern}.diff"	
							patch --quiet "${scriptfile}" < ./hooks_${pattern}.diff || \
								(info -e "Something wen't wrong while patching ${scriptfile}" && return 127)
							;;
						inside )
							# NOTE: replace inside specific function
							# example: replace#inside#build()#make#cmake
							info -m "replaces '${pattern}' with '${value}' in ${context}"
							sed -i "/^${pattern}() {/,/^}$/ s|${value}|${ovalue}|g" "${scriptfile}" ;; 	
						* )
							info -m "replaces '${pattern}' with '${value}' in ${context}"
							sed -i "s|${pattern}|${value}|g" "${scriptfile}" ;;
					esac ;;
			
			remove)
					# remove#context#pattern
					case ${context} in 
						global )
							info -m "removes '${pattern//\'/}' from '${context}'"
							sed -i "s|${pattern}||g" "${scriptfile}"
							;;
						function ) 
							info -m "removes '${pattern//\'/}' from '${scriptfile}'"
							sed -i "/${pattern}/,/^}/d" "${scriptfile}"
						;;
						inside )
							value="$(echo ${value} | sed 's|/|\\/|g')"
							info -m "removes inside '${pattern//\'/}' value '${value}'"
							sed -i "/^${pattern}/,/^}$/ {/${value}/d}" "${scriptfile}" 
							;; 	
						* ) 
							info -m "removes '${pattern//\'/}' from '${context}'"
							# if makedepends/optdepends/depends
							#[[ ${context} =~ depends$ ]] && \
							#pattern="${pattern}[<>=]*\(: \|\)[a-z0-9.{$}\-]*" 
							# junk the quotes too
							sed -i "/${context}/,/)$/ s|[[:blank:]]*['\"]*${pattern}['\"]*||g" "${scriptfile}" 	
						;;
				esac ;;
			insert ) 
					case ${context} in 
						function ) 
								[[ ! -f ${CST_CONFIGDIR}/${package}/PKGBUILD.${pattern} ]] && \
								echo "File 'PKGBUILD.${pattern}' doesn't exist in '$CONFIGDIR'" && exit 1 
							;;
						inside )
						;;
					esac ;;
					
			*)
				info -e "unknown action '${action}'" 1>&2
				exit 255
				;;
		esac
	done
	
	E_CODE=$(error_handling)
	[[ $E_CODE != 0 ]] && return $E_CODE
	
	(( $VERBOSE )) && \
		${DIFFCMD} "${originalscriptfile}" "${scriptfile}"
	
	return 0
}

################################################
VERBOSE=0 
PATCH=0
MODIFY=0
E_CODE=0
while [ "$#" -ne "0" ]; do
	case $1 in
		-h|--help)
			usage
			exit 0
			;;
		-m|--modify) # show diff stdout 
			MODIFY=1
			;;
		--vimdiff| -v)
			[[ $(type -p vim) ]] && DIFFCMD="vim -d" && VERBOSE=1 \
				|| info -w 'vim was not found' 1>&2
			;;
		--verbose ) 
			VERBOSE=1 ;;
	esac
	shift
done

if [ ! -r ./PKGBUILD ]; then
	info -e 'PKGBUILD not found' 1>&2
	exit 255
fi

# use eval instead of creating a temp file to get pkgname etc
eval $(grep -E '^[[:blank:]]*_?(pkg.*|git.*|name)=' ./PKGBUILD | grep -Ev 'log|\describe')

# copy for modification
cp ./PKGBUILD ./${backupfile}
cp ./PKGBUILD ./${tmpfile} # .work u .tmp

for package in "${pkgname[@]}"
do
	
	# local user prefs take priority
	[[ -d "${CST_LOCALCONFIGDIR}/${package}" ]] && \
		CST_CONFIGDIR=${CST_LOCALCONFIGDIR}
	
	# package doesnt exist in CONFIGDIR/
	[[ ! -d ${CST_CONFIGDIR}/${package} ]] && continue
	
	if [[ -f ${CST_CONFIGDIR}/${package}/${package}.cstpkg ]]; then
		cp "${CST_CONFIGDIR}/${package}/${package}.cstpkg" "./"
	else
		info -e "${package}.cstpkg doesn't exist in ${CST_CONFIGDIR}/${package}"
		exit 255
	fi	
	
	# 1 configfile 2 originalscriptfile 3 scriptfile
	modify_file "./${package}.cstpkg" "./PKGBUILD" "./${tmpfile}" || \
		info -E "code $E_CODE" "$E_CODE"

	(( ${MODIFY} )) && \
		mv ./PKGBUILD.tmp ./PKGBUILD && \
		do_clean

done
exit 0
