#!/bin/bash
#
NAME="cstpkg"
CONFIGDIR="/etc/${NAME}.d"
LOCALCONFIGDIR="${HOME}/.${NAME}"
LIBDIR="/usr/lib/cstpkg"
#LIBDIR="/home/marko/Documents/projects/bash/cstpkg/lib"

hooksfile="PKGBUILD.func"
tmpfile="PKGBUILD.tmp" 
backupfile="PKGBUILD.original"

# use colordiff if it's available
[[ $(type -p colordiff) ]] && DIFFCMD="colordiff -ub" || DIFFCMD="diff -ub"

# define colors
R="$(tput bold)$(tput setaf 1)"
G="$(tput bold)$(tput setaf 2)"
B="$(tput bold)$(tput setaf 4)"
Y="$(tput bold)$(tput setaf 3)"
W="$(tput bold)$(tput setaf 7)"
w="$(tput setaf 7)"
N="$(tput sgr0)"

info(){
	local msgtype="$1"
	case $msgtype in
		-m ) printf "%s\n" " ${G}:::${N} $2" 	;; 
		-e ) printf "%s\n" " ${R}:E:${N} $2"; exit 254 ;;
		-w ) printf "%s\n" " ${Y}:W:${N} $2" 	;; 
		-a ) printf "%s\n" "  -> $2" ;; 
	esac
}

# dont need this but I created it because maybe more idea will come
include(){
	local modules="$@"
	
	for module in ${modules[@]} ; do
		[[ -e ${LIBDIR}/${module}.bash ]] && \
			source "${LIBDIR}/${module}.bash" || notfound+="${module} "
	done

	[[ ! -z $notfound ]] && 
	for i in ${notfound}; do
		info -w "Lib '${W}$i${N}' doesn't exist"
	done
}

validate_and_copy_file(){
	local file=${1}

	# checking exsistance of hooks file
	[[ ! -f ${CONFIGDIR}/${package}/${file} ]] && \
		info -e "File $file doen't exist" && exit 1

	cp ${CONFIGDIR}/${package}/${file} "./"

}

clean(){
		local destroy="${hooksfile} ${tmpfile} ${tmpfile}.orig hooks_* *.cstpkg"
		info -m "Removing work files bellow:"

		for i in ${destroy[@]}; do 
			[[ -f $i ]] && info -a "$i" && rm $i
		done
		
}

modify_file()
{

	local configfile=$1
	local originalscriptfile=$2
	local scriptfile=$3
	
	# NOTE: DO I NEED THIS 
	# if the customize file is executable, run it, then we're done.
	if [ -x "${configfile}" ]; then
		info -m "${configfile} is executable, so treating it as a script instead of config"
		"${configfile}" "${originalscriptfile}" "${scriptfile}" && return 0 || exit 1
	fi

	grep "^%" ${configfile} |
	while read -r action context pattern; do
		case ${action} in
			%config )
					include savedconfig
					restore_config "${context}"
				;;
			# TODO: add strict nonstrict 	
			* )
				info -e "There is no such action: ${action}"
				;;
		esac
	done

	grep --invert-match "\(^#\|^$\|^%\)" ${configfile} |
	while IFS='#' read -r action context pattern value ovalue; do
		case ${action} in
			replace)
					#value="${value//\'}"
					case ${context} in
						global ) 
							info -m "replaces '${pattern}' with '${value}' in ${context}"
							case ${pattern} in
								makedepends|optdepends|depends)
									pattern="${pattern}[<>=]*\(: \|\)[a-z0-9.{$}\-]*"
									sed -i "/^${context}=/,/)$/ s|${pattern}|${value}|g" "${scriptfile}" ;;
								* )
									sed -i "s|${pattern}|${value}|g" "${scriptfile}" ;;
							esac ;;
						function ) 
							#	NOTE:	use#file#hook#function name#	
							info -m "diff hook '${pattern}' from ${hooksfile}"
							
							validate_and_copy_file "${hooksfile}"

							#<(sed -n "/${value}/,/^}/p" "./PKGBUILD.hooks" ) \
							diff -ub <(sed -n "/${pattern}/,/^}/p" ${scriptfile}) \
							<(sed -n "/${pattern}/,/^}/p" "./${hooksfile}" ) \
							> ./hooks_${pattern}.diff
							 
							info -m "Patching ${scriptfile} with ./hook_${pattern}.diff"	
							patch --quiet "${scriptfile}" < ./hooks_${pattern}.diff || \
							info -w "Something wen't wrong while patching ${scriptfile}"
							;;
						inside )
							info -m "replaces '${pattern}' with '${value}' in ${context}"
							# NOTE: replace inside specific function
							sed -i "/^${pattern}() {/,/^}$/ s|${value}|${ovalue}|g" "${scriptfile}" ;; 	
						* )	
							info -m "replaces '${pattern}' with '${value}' in ${context}"
							sed -i "s|${pattern}|${value}|g" "${scriptfile}" ;;
					esac ;;
			
			remove)
					# remove#context#pattern
					case ${context} in 
						global )
							info -m "removes '${pattern//\'/}' from '${context}'"
							sed -i "s|${pattern}||g" "${scriptfile}"
							;;
						function ) 
							info -m "removes '${pattern//\'/}' from '${scriptfile}'"
							sed -i "/${pattern}/,/^}/d" "${scriptfile}"
						;;
						inside )
							value="$(echo ${value} | sed 's|/|\\/|g')"
							info -m "removes inside '${pattern//\'/}' value '${value}'"
							sed -i "/^${pattern}/,/^}$/ {/${value}/d}" "${scriptfile}" 
							;; 	
						* ) 
							info -m "removes '${pattern//\'/}' from '${context}'"
							# if makedepends/optdepends/depends
							#[[ ${context} =~ depends$ ]] && \
							#pattern="${pattern}[<>=]*\(: \|\)[a-z0-9.{$}\-]*" 
							# junk the quotes too
							sed -i "/${context}/,/)$/ s|[[:blank:]]*['\"]*${pattern}['\"]*||g" "${scriptfile}" 	
						;;
				esac ;;
			insert ) 
					case ${context} in 
						function ) 
								[[ ! -f ${CONFIGDIR}/${package}/PKGBUILD.${pattern} ]] && \
								echo "File 'PKGBUILD.${pattern}' doesn't exist in '$CONFIGDIR'" && exit 1 
							;;
						inside )
						;;
					esac ;;
					
			*)
				info -e "unknown action '${action}'" 1>&2
				;;
		esac
	done
	
	[[ $VERBOSE -eq 1 ]] && \
		${DIFFCMD} "${originalscriptfile}" "${scriptfile}" 
	
	return 0
}

################################################
VERBOSE=0
PATCH=0
MODIFY=0
while [ "$#" -ne "0" ]; do
	case $1 in
		-h|--help)
			usage
			exit 0
			;;
		-m|--modify) # show diff stdout 
			MODIFY=1
			;;
		--vimdiff| -v)
			[[ $(type -p vim) ]] && DIFFCMD="vim -d" && VERBOSE=1 \
				|| info -w 'vim was not found' 1>&2
			;;
		--verbose ) 
			VERBOSE=1 ;;
	esac
	shift
done

if [ ! -r ./PKGBUILD ]; then
	info -e 'PKGBUILD not found' 1>&2
	exit 1
fi

# use eval instead of creating a temp file to get pkgname etc
eval $(grep -E '^[[:blank:]]*_?(pkg.*|git.*|name)=' ./PKGBUILD)

# copy for modification
cp ./PKGBUILD ./${backupfile}
cp ./PKGBUILD ./${tmpfile} # .work u .tmp

for package in "${pkgname[@]}"
do
	
	# local user prefs take priority
	[[ -d "${LOCALCONFIGDIR}/${package}" ]] && \
		CONFIGDIR=${LOCALCONFIGDIR}
	
	# package doesnt exist in CONFIGDIR/
	[[ ! -d ${CONFIGDIR}/${package} ]] && continue
	
	if [[ -f ${CONFIGDIR}/${package}/${package}.cstpkg ]]; then
		cp "${CONFIGDIR}/${package}/${package}.cstpkg" "./"
	else
		info -e "${package}.cstpkg doesn't exist in $CONFIGDIR/${package}" 
		exit 255
	fi	
	
	# make any changes to PKGBUILD.custom
	# 1 configfile 2 originalscriptfile 3 scriptfile
	modify_file "./${package}.cstpkg" "./PKGBUILD" "./${tmpfile}" || exit 1

	if [ ${MODIFY} -eq 1 ]; then
		#mv ./PKGBUILD.tmp ./PKGBUILD
		#clean all files
		clean
	fi

done
exit 0
